// Generated by CoffeeScript 2.2.2
var G, Q, here, k, main, mode, next, node, prev;

G = {
  root: {
    html: "<section><h2>Welcome!</h2><p>Please click Next to continue.</p></section>",
    prev: [],
    next: ['r1'],
    status: 'U',
    type: 'R'
  },
  r1: {
    html: "<section><h2>Part 1: Graphics</h2><img src='https://cdn.glitch.com/af29f83a-f749-48b2-9c76-0d60e29e3f45%2Fperf.png' alt=''><p>Text here...</p><img src='https://cdn.glitch.com/af29f83a-f749-48b2-9c76-0d60e29e3f45%2Fpendulum.gif' alt=''><p>More text here...</p><img src='https://cdn.glitch.com/af29f83a-f749-48b2-9c76-0d60e29e3f45%2Fgraph.png' alt=''></section>",
    prev: ['root'],
    next: ['r2'],
    status: 'U',
    type: 'R'
  },
  r2: {
    html: "<section><h2>Part 2: Video</h2><video src='https://cdn.glitch.com/af29f83a-f749-48b2-9c76-0d60e29e3f45%2FWikipedia_Edit_2014.webm.480p.mp4?1519852975134' controls></video></section>",
    prev: ['r1'],
    next: ['r3'],
    status: 'L',
    type: 'Q',
    q: [0, 1, 2]
  },
  r3: {
    html: "<section><h2>Part 3: KaTeX</h2><p>With HTML subscript and superscript:</p><p>NaHCO<sub>3 (s)</sub> &rarr; Na<sup>+</sup><sub>(aq)</sub> + HCO<sub>3</sub><sup>-</sup><sub>(aq)</sub></p><p>With KaTeX:</p><p id='katex'></p></section>",
    prev: ['r2'],
    next: [],
    status: 'L',
    type: 'T',
    q: [3, 4, 5, 6, 7]
  }
};

// Widgets
$('button').button();

// Pre-process
main = $('#main');

for (k in G) {
  node = G[k];
  main.append(node.html = $(node.html));
}

here = G.root;

here.html.addClass('show');

mode = 'R';

katex.render('f(x) = \\int_{-\\infty}^\\infty \\hat f(\\xi)\\,e^{2 \\pi i \\xi x} \\,d\\xi', $('#katex')[0]);

// Event handlers
next = $('#next').click(() => {
  if (here.next[0]) {
    here.html.removeClass('show');
    here = G[here.next[0]];
    here.html.addClass('show');
    prev.toggleClass('hide', here.prev.length < 1);
    return next.toggleClass('hide', here.next.length < 1);
  }
});

prev = $('#prev').click(() => {
  if (here.prev[0]) {
    here.html.removeClass('show');
    here = G[here.prev[0]];
    here.html.addClass('show');
    prev.toggleClass('hide', here.prev.length < 1);
    return next.toggleClass('hide', here.next.length < 1);
  }
});
